export const productsData = [
  {
    id: 871,
    prod_id: "04888ac8-85e2-11ed-9717-00155d212c06",
    sku: "1157600939",
    name: "The Silent Patient",
    slug: "the-silent-patient",
    description: "",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["New node", "Thrillar"],
    tags: [],
    new_arriaval: 0,
    price: {
      max: 650,
      min: 650,
      base_cost: 200,
      base_sale: 650,
    },
    variants: [
      {
        id: 2071,
        sold: 1,
        added: 6,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 200,
          selling_price: 650,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 1,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570909172_675365760_product_gallery.jpeg",
        selling_price: 650,
        shipping_attribute: {
          width: 1,
          height: 1,
          length: 1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 5,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: 5,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: "thumbnail",
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570909172_675365760_product_gallery.jpeg",
    },
    gallery: [],
    video: {},
    seo: {
      title: "The Silent Patient",
      keywords: "",
      description: "",
    },
    checkout_url:
      "https://bookshop.webmanza.com/the-silent-patient?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1663527701,
    created_at: 1663570929,
    updated_at: 1663570929,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 870,
    prod_id: "048888e5-85e2-11ed-9717-00155d212c06",
    sku: "4832350041",
    name: "I Am Watching you",
    slug: "i-am-watching-you",
    description: "",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["New node", "Thrillar"],
    tags: [],
    new_arriaval: 0,
    price: {
      max: 600,
      min: 600,
      base_cost: 200,
      base_sale: 600,
    },
    variants: [
      {
        id: 2070,
        sold: 0,
        added: 6,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 200,
          selling_price: 600,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 1,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570881049_377141626_product_gallery.jpeg",
        selling_price: 600,
        shipping_attribute: {
          width: 1,
          height: 1,
          length: 1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 5,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: 5,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: "thumbnail",
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570881049_377141626_product_gallery.jpeg",
    },
    gallery: [],
    video: {},
    seo: {
      title: "I Am Watching you",
      keywords: "",
      description: "",
    },
    checkout_url:
      "https://bookshop.webmanza.com/i-am-watching-you?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1663527676,
    created_at: 1663570899,
    updated_at: 1663570899,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 869,
    prod_id: "048886f9-85e2-11ed-9717-00155d212c06",
    sku: "8054066778",
    name: "Girl At the Edge",
    slug: "girl-at-the-edge",
    description: "<p>Girl At the Edge</p>",
    additional_info: [
      {
        body: [],
        label: "Overview",
      },
    ],
    overview: '{"has": false, "url": "", "data": [], "target": "_blank"}',
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Thrillar"],
    tags: ["BEST SELLER", "FEATURED", "NEW ARRIVALS"],
    new_arriaval: 0,
    price: {
      max: 600,
      min: 600,
      base_cost: 200,
      base_sale: 600,
    },
    variants: [
      {
        id: 2069,
        sold: 0,
        added: 6,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 200,
          selling_price: 600,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570856356_313229747_product_gallery.jpeg",
        selling_price: 600,
        shipping_attribute: {
          width: 1,
          height: 1,
          length: 1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 3,
        in_stock: 6,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: "1694088988729-139201663570856356313229747productgalleryjpeg",
      src: "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/9_1694088988729-139201663570856356313229747productgalleryjpeg.jpeg",
    },
    gallery: [
      {
        alt: "1694088988729-139201663570856356313229747productgalleryjpeg",
        src: "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/9_1694088988729-139201663570856356313229747productgalleryjpeg.jpeg",
      },
      {
        alt: "thumbnail",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570856356_313229747_product_gallery.jpeg",
      },
      {
        alt: "1694088988729-139201663570856356313229747productgalleryjpeg",
        src: "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/9_1694088988729-139201663570856356313229747productgalleryjpeg.jpeg",
      },
      {
        alt: "thumbnail",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570856356_313229747_product_gallery.jpeg",
      },
      {
        alt: "1694088988729-139201663570856356313229747productgalleryjpeg",
        src: "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/9_1694088988729-139201663570856356313229747productgalleryjpeg.jpeg",
      },
      {
        alt: "thumbnail",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1663570856356_313229747_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "Girl At the Edge",
      keywords: "",
      description: "",
    },
    checkout_url:
      "https://bookshop.webmanza.com/girl-at-the-edge?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "faridul",
    available_at: 1663527651,
    created_at: 1663570873,
    updated_at: 1694089010,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 621,
    prod_id: "2380f791-3f14-11ed-9717-00155d212621",
    sku: "8831752598",
    name: "THE STORY OF MY LIFE",
    slug: "the-story-of-my-life",
    description: "<p>THE STORY OF MY LIFE</p>",
    additional_info: [
      {
        body: [],
        label: "Overview",
      },
    ],
    overview: '{"has": false, "url": "", "data": [], "target": "_blank"}',
    price_visibility: 1,
    cart_visibility: 1,
    brand: "Book",
    categories: ["Advanture"],
    tags: ["FEATURED", "NEW ARRIVALS"],
    new_arriaval: 0,
    price: {
      max: 300,
      min: 300,
      base_cost: 100,
      base_sale: 300,
    },
    variants: [
      {
        id: 1517,
        sold: 0,
        added: 11,
        price: {
          end_at: 1663701300,
          camp_id: 68,
          start_at: 1663528500,
          cost_price: 100,
          selling_price: 300,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224896219_373376536_product_gallery.jpeg",
        selling_price: 300,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 3,
        in_stock: 11,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: "null",
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224922260_992809916_product_gallery.jpeg",
    },
    gallery: [
      {
        alt: "null",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224922260_992809916_product_gallery.jpeg",
      },
      {
        alt: "null",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224896219_373376536_product_gallery.jpeg",
      },
      {
        alt: "null",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224922260_992809916_product_gallery.jpeg",
      },
      {
        alt: "null",
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224896219_373376536_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "THE STORY OF MY LIFE",
      keywords: "",
      description: "",
    },
    checkout_url:
      "https://bookshop.webmanza.com/the-story-of-my-life?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "faridul",
    available_at: 1660181742,
    created_at: 1660225021,
    updated_at: 1694089036,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 620,
    prod_id: "2380f71a-3f14-11ed-9717-00155d212620",
    sku: "3103699095",
    name: "Witers Sisters",
    slug: "witers-sisters",
    description: "BY ROBIN OLIVEIRA",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Romance"],
    tags: ["BEST SELLER"],
    new_arriaval: 0,
    price: {
      max: 450,
      min: 450,
      base_cost: 150,
      base_sale: 450,
    },
    variants: [
      {
        id: 1516,
        sold: 0,
        added: 0,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 150,
          selling_price: 450,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224743307_243733824_product_gallery.jpeg",
        selling_price: 450,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 0,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224752546_748616568_product_gallery.jpeg",
    },
    gallery: [
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224752546_748616568_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224743307_243733824_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "Witers Sisters",
      keywords: "",
      description: "BY ROBIN OLIVEIRA",
    },
    checkout_url: "https://bookshop.webmanza.com/witers-sisters?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660181578,
    created_at: 1660224872,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 619,
    prod_id: "2380f69a-3f14-11ed-9717-00155d212619",
    sku: "3136134652",
    name: "Wrong Place, Wrong Time",
    slug: "wrong-place-wrong-time",
    description: "",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Romance"],
    tags: ["NEW ARRIVALS"],
    new_arriaval: 0,
    price: {
      max: 300,
      min: 300,
      base_cost: 100,
      base_sale: 300,
    },
    variants: [
      {
        id: 1515,
        sold: 0,
        added: 5,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 100,
          selling_price: 300,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224624860_408038676_product_gallery.jpeg",
        selling_price: 300,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 5,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224624860_408038676_product_gallery.jpeg",
    },
    gallery: [],
    video: {},
    seo: {
      title: "Wrong Place, Wrong Time",
      keywords: "",
      description: "",
    },
    checkout_url:
      "https://bookshop.webmanza.com/wrong-place-wrong-time?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660181482,
    created_at: 1660224772,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 618,
    prod_id: "2380f60c-3f14-11ed-9717-00155d212618",
    sku: "6201230953",
    name: "Before You Know My Name",
    slug: "before-you-know-my-name",
    description: "Romantic Story book by Jacqeline Bublitz",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Romance"],
    tags: ["BEST SELLER"],
    new_arriaval: 0,
    price: {
      max: 300,
      min: 300,
      base_cost: 150,
      base_sale: 300,
    },
    variants: [
      {
        id: 1514,
        sold: 0,
        added: 10,
        price: {
          end_at: null,
          camp_id: null,
          start_at: null,
          cost_price: 150,
          selling_price: 300,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224243020_816637564_product_gallery.jpeg",
        selling_price: 300,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 10,
      },
    ],
    discount: {
      type: "Percentage",
      amount: 0,
      percent: 10,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660224243020_816637564_product_gallery.jpeg",
    },
    gallery: [],
    video: {},
    seo: {
      title: "Before You Know My Name",
      keywords: "",
      description: "Romantic Story book by Jacqeline Bublitz",
    },
    checkout_url:
      "https://bookshop.webmanza.com/before-you-know-my-name?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660181084,
    created_at: 1660224415,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: true,
    wishlist: false,
  },
  {
    id: 617,
    prod_id: "2380f568-3f14-11ed-9717-00155d212617",
    sku: "6042450333",
    name: "The Fall Of Numenor",
    slug: "the-fall-of-numenor",
    description: "Adventure by J.R.R Tolkien",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["New node", "Advanture"],
    tags: ["FEATURED"],
    new_arriaval: 0,
    price: {
      max: 450,
      min: 450,
      base_cost: 150,
      base_sale: 450,
    },
    variants: [
      {
        id: 1513,
        sold: 0,
        added: 15,
        price: {
          end_at: 1663701300,
          camp_id: 68,
          start_at: 1663528500,
          cost_price: 150,
          selling_price: 450,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222651783_148273922_product_gallery.jpeg",
        selling_price: 450,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 15,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222696124_990363908_product_gallery.jpeg",
    },
    gallery: [
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222696124_990363908_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222651783_148273922_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222651783_148273922_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222696124_990363908_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "The Fall Of Numenor",
      keywords: "",
      description: "Adventure by J.R.R Tolkien",
    },
    checkout_url:
      "https://bookshop.webmanza.com/the-fall-of-numenor?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660179505,
    created_at: 1660222809,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 616,
    prod_id: "2380f4ab-3f14-11ed-9717-00155d212616",
    sku: "3076737180",
    name: "NIGHT Film",
    slug: "night-film",
    description: "A Horror Series by MARISHA PESSL",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Horror"],
    tags: ["MOST POPULER"],
    new_arriaval: 0,
    price: {
      max: 600,
      min: 600,
      base_cost: 200,
      base_sale: 600,
    },
    variants: [
      {
        id: 1512,
        sold: 0,
        added: 5,
        price: {
          end_at: 1660959420,
          camp_id: 51,
          start_at: null,
          cost_price: 200,
          selling_price: 600,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222507747_881763305_product_gallery.jpeg",
        selling_price: 600,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 5,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222555773_570305823_product_gallery.jpeg",
    },
    gallery: [
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222555773_570305823_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222507747_881763305_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "NIGHT Film",
      keywords: "",
      description: "A Horror Series by MARISHA PESSL",
    },
    checkout_url: "https://bookshop.webmanza.com/night-film?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660179367,
    created_at: 1660222702,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
  {
    id: 615,
    prod_id: "2380f2d8-3f14-11ed-9717-00155d212615",
    sku: "3931101516",
    name: "KITE RUNNER",
    slug: "kite-runner",
    description: "Horror Series book by KHALED HOSSEINI",
    additional_info: null,
    overview: null,
    price_visibility: 1,
    cart_visibility: 1,
    brand: null,
    categories: ["Horror"],
    tags: ["FEATURED"],
    new_arriaval: 0,
    price: {
      max: 400,
      min: 400,
      base_cost: 150,
      base_sale: 400,
    },
    variants: [
      {
        id: 1511,
        sold: 0,
        added: 11,
        price: {
          end_at: 1660959420,
          camp_id: 51,
          start_at: null,
          cost_price: 150,
          selling_price: 400,
          general_discount_amount: 0,
          campaign_discount_amount: 0,
        },
        value1: "Default",
        value2: null,
        value3: null,
        option1: "Variant",
        option2: null,
        option3: null,
        canceled: 0,
        returned: 0,
        committed: 0,
        delivered: 0,
        thumbnail:
          "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222414579_604084895_product_gallery.jpeg",
        selling_price: 400,
        shipping_attribute: {
          width: 0.1,
          height: 0.1,
          length: 0.1,
          weight: 1,
          length_class: "in",
          weight_class: "kg",
        },
        low_stock_threshold: 2,
        in_stock: 11,
      },
    ],
    discount: {
      type: null,
      amount: 0,
      percent: 0,
      general_discount_amount: 0,
      campaign_discount_amount: 0,
    },
    campaigns: [],
    tax: {
      name: null,
      rate: null,
    },
    package_unit: 1,
    inventory: {
      managed: false,
      avilable: null,
    },
    rating: {
      avg: 0,
      total: 0,
    },
    thumbnail: {
      alt: null,
      src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222458112_926656464_product_gallery.jpeg",
    },
    gallery: [
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222458112_926656464_product_gallery.jpeg",
      },
      {
        alt: null,
        src: "https://api.admin.webmanza.com/assets/product/gallery/139_20_1660222414579_604084895_product_gallery.jpeg",
      },
    ],
    video: {},
    seo: {
      title: "KITE RUNNER",
      keywords: "",
      description: "Horror Series book by KHALED HOSSEINI",
    },
    checkout_url: "https://bookshop.webmanza.com/kite-runner?checkout=true",
    has_physical_delivery: 1,
    has_digital_delivery: 0,
    product_type: "Physical",
    product_status: "Published",
    sort: 0,
    created_by: "bookshop",
    updated_by: "bookshop",
    available_at: 1660179273,
    created_at: 1660222562,
    updated_at: 1665376609,
    in_stock: null,
    on_sale: false,
    wishlist: false,
  },
];
