export const storeInfo = {
  theme_info: {
    slider_g5BCN7: {
      list: [
        {
          title: "",
          btn_text: "",
          isEdited: true,
          subtitle: "",
          banner_url:
            "https://sg-api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1680588807441-bookshopjpg.jpeg",
          redirect_url: "https://dummyimage.com/1920x520/969496/ffffff.jpg",
          mobile_banner_url:
            "https://sg-api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1680588811429-bookshop-1200-730-pxjpg.jpeg",
        },
      ],
      sort: "0",
      status: true,
      setting: {
        slider: {
          dots: false,
          arrow: true,
          autoplay: true,
        },
        layout_type: "slider",
      },
    },
    policy_Vt2LNx: {
      list: [
        {
          icon: "",
          title: "",
          content: "",
        },
      ],
      sort: "1",
      status: true,
      setting: {
        show: {
          mobile_row: "3",
          tablet_row: "5",
          desktop_row: "6",
        },
      },
    },
    category_1JXLtF: {
      list: [
        {
          id: 858,
          url: "",
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          name: "Story",
          thumb:
            "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1685613459310-1659965662-51d9xzdhiwl-sl500-jpg.jpeg",
          isEdited: false,
          description: "Story",
        },
        {
          id: 863,
          url: "",
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          name: "Academic",
          thumb:
            "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1685613527566-books-300x199jpg.jpeg",
          isEdited: false,
          description: "Academic",
        },
        {
          id: 868,
          url: "",
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          name: "BCS",
          thumb:
            "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1685613931864-bcs-preparation-guidesjpg.jpeg",
          isEdited: false,
          description: "BCS",
        },
        {
          id: 869,
          url: "",
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          name: "Jobs",
          thumb:
            "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1685614080990-how-to-take-primary-school-job-preparation-simply-and-easilyjpg.jpeg",
          isEdited: true,
          description: "Jobs",
        },
      ],
      sort: "2",
      title: "Sample Title",
      status: true,
      details: "Sample Offer",
      setting: {
        show: {
          mobile_row: "3",
          tablet_row: "5",
          desktop_row: "6",
          no_of_item_show: "10",
        },
        slider: {
          dots: false,
          arrow: true,
          autoplay: true,
        },
        template: "hover-box-grid-slider",
        layout_type: "slider",
      },
      subtitle: "Sample Offer",
    },
    collectionBox_cqZJao: {
      list: [
        {
          id: 858,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
        {
          id: 863,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
      ],
      sort: "3",
      title: "Special Product",
      status: true,
      details: "",
      setting: {
        show: {
          mobile_row: "2",
          tablet_row: "5",
          desktop_row: "5",
          no_of_item_show: "10",
        },
        slider: {
          dots: false,
          arrow: true,
          autoplay: true,
        },
        template: "tab3-slider-grid",
        layout_type: "grid",
      },
      subtitle: "",
    },
    image_osrc9o: {
      url: "https://api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1685939726683-untitled-design-17jpg.jpeg",
      sort: "4",
      fluid: true,
      status: true,
    },
    collectionBox_pvKgOA: {
      list: [],
      sort: "5",
      title: "",
      status: true,
      details: "",
      setting: {
        show: {
          mobile_row: "3",
          tablet_row: "5",
          desktop_row: "6",
          no_of_item_show: "10",
        },
        slider: {
          dots: false,
          arrow: true,
          autoplay: true,
        },
        template: "collection4-slider-grid",
        layout_type: "grid",
      },
      subtitle: "",
    },
    tags_7MfPOl: {
      list: [
        {
          id: 89,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
        {
          id: 90,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
        {
          id: 91,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
        {
          id: 92,
          banner_url: "",
          redirect_url: "",
          mobile_banner_url: "",
        },
      ],
      sort: 6,
      title: "",
      status: true,
      details: "",
      setting: {
        show: {
          mobile_row: "3",
          tablet_row: "5",
          desktop_row: "6",
          no_of_item_show: "10",
        },
        slider: {
          dots: false,
          arrow: true,
          autoplay: true,
        },
        template: "tag-banner-slider-grid",
        layout_type: "grid",
      },
      subtitle: "",
    },
    service_PWt3Ot: {
      list: [
        {
          icon: "FaShoppingCart",
          title: "free shipping",
          content: "<p>free shipping world wide</p>",
        },
        {
          icon: "FaRegClock",
          title: "24 X 7 service",
          content: "<p>online service for new customer</p>",
        },
        {
          icon: "FaTelegramPlane",
          title: "festival offer",
          content: "<p>new online special festival offer<br></p>",
        },
      ],
      sort: "7",
      status: true,
      setting: {
        show: {
          mobile_row: "3",
          tablet_row: "5",
          desktop_row: "6",
        },
      },
    },
  },
  store_info: {
    msisdn: "01708133969",
    email: "bookshop@webmanza.com",
    domain: "bookshop.webmanza.com",
    site_title: "Bookshop Studio",
    business_name: "Bookshop Studio",
    business_address: "Rangs Babylonia Level 6",
    office_address: "Rangs Babylonia Level 6",
    country: "BD",
    lang: "",
    timezone: "Asia/Dhaka",
    currency: "৳",
    published: 1,
    active_time: 1660217604,
    expire_time: 1924884000,
    tid: "cd699142-2d20-11ed-9717-00155d212c06",
    store_category: "Fashion, Clothing & Accessories",
    store_cat_id: 1,
    marketing_tools: null,
  },
  logo: {
    fav_icon: "fav_icon",
    fav_logo:
      "https://sg-api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1680588624693-untitled-design-6jpg.jpeg",
    dark_logo:
      "https://sg-api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1680588621512-untitled-220-56-px-3jpg.jpeg",
    light_logo:
      "https://sg-api.admin.webmanza.com/4571dbd0-2cd7-11ed-9717-00155d212c06/uploads/20_1680588618474-untitled-220-56-px-3jpg.jpeg",
  },
  hotline: {
    text: "Live Support",
    email: "",
    mobile: "8801708133969",
  },
  general_settings: {
    dark_mode: false,
    layout_type: "ltr",
    shop_layout: "left_sidebar",
    product_view: "style-1",
    show_compare: false,
    show_ratings: true,
    primary_color: "#ff5900",
    show_wishlist: false,
    product_layout: "right_sidebar",
    show_quick_view: true,
  },
  locations: [
    {
      id: "AT",
      email: "info@webmanza.com",
      mobile: "01700705293",
      address: "Dhaka, Bangladesh",
    },
  ],
  header: {
    body: {
      logo_section: true,
      primary_menu: [
        {
          id: 105,
          icon: "",
          path: "/page/about-us",
          text: "About Us",
          custom: false,
          parent: 0,
          url_type: "page",
          droppable: true,
        },
        {
          id: 104,
          icon: "",
          path: "/page/contact-us",
          text: "Contact Us",
          custom: false,
          parent: 0,
          url_type: "page",
          droppable: true,
        },
        {
          id: 103,
          icon: "",
          path: "/page/faq",
          text: "FAQ",
          custom: false,
          parent: 0,
          url_type: "page",
          droppable: true,
        },
      ],
      category_menu: [
        {
          id: 858,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "story",
          text: "Story",
          custom: false,
          parent: 0,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 859,
          icon: "https://api.admin.webmanza.com/cat_icon/040-face mask.png",
          path: "horror-f71aj1j-j3gm67",
          text: "Horror",
          custom: false,
          parent: 858,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 860,
          icon: "https://api.admin.webmanza.com/cat_icon/003-rings.png",
          path: "thrillar-7gext4",
          text: "Thrillar",
          custom: false,
          parent: 858,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 861,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "romance",
          text: "Romance",
          custom: false,
          parent: 858,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 862,
          icon: "https://api.admin.webmanza.com/cat_icon/018-bandana.png",
          path: "advanture-xz6ds",
          text: "Advanture",
          custom: false,
          parent: 858,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 863,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "academic",
          text: "Academic",
          custom: false,
          parent: 0,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 864,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "bba",
          text: "BBA",
          custom: false,
          parent: 863,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 865,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "mba",
          text: "MBA",
          custom: false,
          parent: 863,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 866,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "medical",
          text: "Medical",
          custom: false,
          parent: 863,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 867,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "buet",
          text: "BUET",
          custom: false,
          parent: 863,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 868,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "bcs",
          text: "BCS",
          custom: false,
          parent: 0,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 869,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "jobs",
          text: "Jobs",
          custom: false,
          parent: 0,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 870,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "bank-amp-finance",
          text: "Bank &amp; Finance",
          custom: false,
          parent: 869,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 871,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "govt-jobs",
          text: "Govt Jobs",
          custom: false,
          parent: 869,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 1047,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "new-node",
          text: "New node",
          custom: false,
          parent: 871,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 1048,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "new-node-18gv1c",
          text: "New node",
          custom: false,
          parent: 1047,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 1049,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "new-node-11j9l1",
          text: "New node",
          custom: false,
          parent: 1048,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
        {
          id: 1050,
          icon: "https://api.admin.webmanza.com/assets/product/gallery/107_2_1656930406379_346953729_product_gallery.png",
          path: "new-node-40tszq",
          text: "New node",
          custom: false,
          parent: 1049,
          megaMenu: false,
          url_type: "category",
          droppable: true,
        },
      ],
      hotline_section: true,
    },
    layout: "left-logo-header",
    search: true,
    sticky: true,
    styles: {
      topbar: {
        background: {
          type: "gradient",
          value: {
            end: 100,
            type: "linear",
            start: 0,
            color1: {
              a: 1,
              b: 22,
              g: 114,
              r: 240,
            },
            color2: {
              a: 1,
              b: 0,
              g: 142,
              r: 255,
            },
            direction: 180,
          },
        },
      },
    },
    bgColor: "",
    bgImage: "",
    category: true,
    langConfig: true,
  },
  seo: {
    meta_title: "Bookshop Studio",
    meta_keywords: "Bookshop, Studio",
    meta_description: "Bookshop Studio",
  },
  footer: {
    body: {
      method: "",
      column1: {
        list: {
          logo_4ECq53: {
            sort: 0,
            allow: true,
          },
          text_oaT6SY: {
            content:
              "<p>A bookshop is a specialized retail establishment that primarily sells \nbooks, both fiction and non-fiction, across various genres and subjects.\n Often a sanctuary for bibliophiles, a bookshop might also offer related\n items such as magazines, newspapers, stationery, and sometimes music or\n movies.</p>",
          },
          social_Onen8u: {
            list: [
              {
                url: "#",
                icon: "FaFacebookSquare",
              },
            ],
          },
        },
        logo_section: true,
        info_asdfasdf: [],
        social_skdjfsd: [],
      },
      column2: {
        list: {
          newsletter_nvABLM: {
            sort: 0,
            title: "KNOW IT ALL FIRST!",
            subtitle:
              "Never Miss Anything From WebManza By Signing Up To Our Newsletter.",
          },
        },
        manue_company: [
          {
            type: "page",
            pageId: 1,
          },
          {
            url: "",
            type: "custom",
            title: "",
            pageId: 0,
          },
        ],
      },
      column3: {
        list: {
          location_CRaUgZ: {
            id: "AT",
          },
        },
        manue_support: [
          {
            type: "page",
            pageId: 1,
          },
          {
            url: "",
            type: "custom",
            title: "",
            pageId: 0,
          },
        ],
      },
      column4: {
        list: {
          menubar_87srO8: {
            list: [
              {
                id: 105,
                icon: "",
                path: "/page/about-us",
                text: "About Us",
                custom: false,
                parent: 0,
                url_type: "page",
                droppable: true,
              },
              {
                id: 104,
                icon: "",
                path: "/page/contact-us",
                text: "Contact Us",
                custom: false,
                parent: 0,
                url_type: "page",
                droppable: true,
              },
              {
                id: 103,
                icon: "",
                path: "/page/faq",
                text: "FAQ",
                custom: false,
                parent: 0,
                url_type: "page",
                droppable: true,
              },
              {
                id: 106,
                icon: "",
                path: "/page/return-policy",
                text: "Return Policy",
                custom: false,
                parent: 0,
                url_type: "page",
                droppable: true,
              },
              {
                id: 107,
                icon: "",
                path: "/page/tearms-condisions",
                text: "Tearms & Condisions",
                custom: false,
                parent: 0,
                url_type: "page",
                droppable: true,
              },
            ],
            name: "",
            sort: 0,
          },
        },
        title: "Company",
        locations_lsdlfju: {
          title: "",
          location_ids: [1, 4],
        },
      },
      column5: {},
      column6: {},
      copyright: "",
    },
    layout: "footer-3",
    sticky: false,
    styles: {
      background: {
        type: "color",
        value: {
          a: 1,
          b: 64,
          g: 17,
          r: 26,
        },
      },
    },
  },
};
